#!/usr/bin/env groovy

pipeline {
    agent any

    stages {
        stage('Build-Jar-File') {
            agent {
                docker { image 'maven' }
            }
            steps {
                configFileProvider([configFile(fileId: '37568ccb-b1bc-447a-a416-3793483a5fcc',variable: 'APP_PROPS')]){
                sh 'cp $APP_PROPS src/main/resources/application.properties'
                sh 'mvn package -Dmaven.test.skip=true'
                sh 'mvn clean install -f pom.xml'
                }
            }
        }

        stage('Build-Image') {
            steps {
                script {
                    app = docker.build("gym-project/test")
                }
            }
        }
    }
}